// <auto-generated />
using System;
using Art.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Art.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211220103323_settingSomeData")]
    partial class settingSomeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Art.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageArtist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            Country = "Netherlands",
                            Email = "Sonja@gmail.com",
                            FirstName = "Sonja",
                            ImageArtist = "https://dutch-accent.nl/wp-content/uploads/sonjabrussen.jpg",
                            LastName = "Brussen",
                            PhoneNumber = "0739888159"
                        },
                        new
                        {
                            ArtistId = 2,
                            Country = "Italy",
                            Email = "Marco@gmail.com",
                            FirstName = "Marco",
                            ImageArtist = "https://cdn.singulart.com/artists/pictures/cropped/artwork/base/artist_artwork_6167_67251a429f48bec92ea62a94abc63de9.jpeg",
                            LastName = "Barberio",
                            PhoneNumber = "0739888159"
                        },
                        new
                        {
                            ArtistId = 3,
                            Country = "Russian",
                            Email = "Tatiana@gmail.com",
                            FirstName = "Tatiana",
                            ImageArtist = "https://d3rf6j5nx5r04a.cloudfront.net/nTSKy_xfl-jCkClViyQ6eWWGzMI=/240x240/artists/e/0/9a4985a64d294797bc1af8f94ef6407e.jpg",
                            LastName = "Golovko",
                            PhoneNumber = "0739888159"
                        });
                });

            modelBuilder.Entity("Art.Models.Painting", b =>
                {
                    b.Property<int>("PainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("DrawingYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("PaintingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("PainingId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            PainingId = 1,
                            DrawingYear = "2020",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/ygDxGa-_V-LBxFPO1SkGf0BS4zc=/1120x0/product/5/0/75fffbcf840b4b0ca7844ce74a92d220_opt.jpg",
                            Length = 140,
                            PaintingName = "Silence of nature",
                            PaintingType = "Oil Painting",
                            Price = 280m,
                            Width = 100
                        },
                        new
                        {
                            PainingId = 2,
                            DrawingYear = "2021",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/C775hrN-B1Rl1djwrujZr7N2ESs=/1120x0/product/9/8/324997ae1ef14461ba1ee7ba552b6938_opt.jpg",
                            Length = 52,
                            PaintingName = "Lucky",
                            PaintingType = "Oil Painting",
                            Price = 93m,
                            Width = 42
                        },
                        new
                        {
                            PainingId = 3,
                            DrawingYear = "2021",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/XilzqOuifRkv1zKLP09iWR0eCO4=/1120x0/product/9/8/bfd0972cc5c74aab8b09a4087cdb944b_opt.jpg",
                            Length = 52,
                            PaintingName = "Behind the scene",
                            PaintingType = "Oil painting",
                            Price = 180m,
                            Width = 42
                        },
                        new
                        {
                            PainingId = 4,
                            DrawingYear = "2021",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/oOKee0RsyKA2gneb7h_Yh7HW6Pg=/1120x0/product/9/7/1f60fe1fd06a44d3a64b256e4378f06e_opt.jpg",
                            Length = 92,
                            PaintingName = "All Stars and Stripes",
                            PaintingType = "Acrylic painting",
                            Price = 160m,
                            Width = 92
                        },
                        new
                        {
                            PainingId = 5,
                            DrawingYear = "2021",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/38c6ejyvy2XwIYneBvMWtPj3QOc=/1120x0/product/6/d/f26a45c5bacc417aa22cdac707e85f2e_opt.jpg",
                            Length = 49,
                            PaintingName = "Marco Barberio",
                            PaintingType = "Acrylic painting",
                            Price = 120m,
                            Width = 49
                        },
                        new
                        {
                            PainingId = 6,
                            DrawingYear = "2020",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/lhtIroduPQs7rw2o2xHzq4lQo24=/1120x0/product/5/1/a61eee843cfa4808a1871b0d828e4ba0_opt.jpg",
                            Length = 56,
                            PaintingName = "A Moment",
                            PaintingType = "Watercolour",
                            Price = 102m,
                            Width = 76
                        },
                        new
                        {
                            PainingId = 7,
                            DrawingYear = "2020",
                            Image = "https://d3rf6j5nx5r04a.cloudfront.net/jOpVoXqc7I9FaAiSoCWOpf2erp0=/1120x0/product/5/4/4aef2de04b964796b07576750c42ce5e_opt.jpeg",
                            Length = 56,
                            PaintingName = "Birds-of-Paradise",
                            PaintingType = "Watercolour",
                            Price = 180m,
                            Width = 76
                        });
                });

            modelBuilder.Entity("Art.Models.Painting", b =>
                {
                    b.HasOne("Art.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });
#pragma warning restore 612, 618
        }
    }
}
